### ISSUE TITLE
query to find find Munsell colors by regex

### ISSUE THREAD

**Issue by dbvisel** [privet-kitty/munsell.js#7]
Hi! I'm using munsellToHex from this library to colorize archaeological data sets and it's great! Thanks so much for this. 

A query though: I'm working with very messy datasets, where there's a "color" field, but no validation has happened. So I'm getting a string which sometimes might have something like "7.5YR 8/4" which is great, but as often comes in as something like "yellow 10YR 7/6". What I'd like to do is to pull the "10YR 7/6" out of that string. Is there a good regex for finding valid Munsell color codes? 

It might be useful to have a validator function in this library – because my data's messy, I'm using a `try . . . catch` around my use of `munsellToHex`, though I'd love to not have to send it thousands of bad values, which is what I'm currently doing.

Putting this here in the hopes that somebody's solved this problem in the past – maybe I should dig through your code. Thanks again though!

**Comment by privet-kitty** [comment]
Hi. Thank you for your feedback!

I haven't thought about it, but I guess you'll have a good regex for Munsell code by concatenating some patterns for numeric values. It would be better to think about it after inspecting the actual dataset. Sorry I'm not much help.

**Comment by dbvisel** [comment]
No trouble – I found what I needed by poking through the code and reassembling bits of it. Here's the function I made if it's useful to anyone:

```
const isValidMunsell = (munsellStr) => {
  const hueNames = ["R", "YR", "Y", "GY", "G", "BG", "B", "PB", "P", "RP"];
  const nums = munsellStr
    .split(/[^a-z0-9.-]+/)
    .filter(Boolean)
    .map((str) => Number(str));

  const words = munsellStr.match(/[A-Z]+/);
  if (words === null) {
    return false;
  }

  const hueName = words[0];

  const hueNumber = hueNames.indexOf(hueName);

  if (hueName === "N") {
    // this would have returned [0, nums[0], 0]
    return true;
  } else if (nums.length !== 3) {
    return false;
  } else if (hueNumber === -1) {
    // achromatic

    return false;
  } else {
    return true;
  }
};
```

That returns `true` if it can be parsed as a Munsell color, `false` if it can't. Thanks again for a useful library!
